# Generated by Django 4.1.1 on 2022-09-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
            preserve_default=False,
        ),
    ]
