# Generated by Django 4.1.1 on 2022-09-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_model_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
