# Generated by Django 4.1.1 on 2022-09-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_model_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='image',
        ),
    ]
